development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: # The link you get from the provider of the cloud service that you deploy your code.
  channel_prefix: peerportal_production
